apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gcp-app
  template:
    metadata:
      labels:
        app: gcp-app
    spec:
      containers:
      - name: app
        image: asia-south1-docker.pkg.dev/careful-chess-495403-e6/myrepo/app:latest
        ports:
        - containerPort: 80
        # Make sure your app listens on 0.0.0.0 inside container

---
apiVersion: v1
kind: Service
metadata:
  name: gcp-service
spec:
  selector:
    app: gcp-app
  type: LoadBalancer
  ports:
  - port: 80          # External port
    targetPort: 80  # Container port
